DROP TABLE IF EXISTS tour;
DROP TABLE IF EXISTS tour_feeding_type;
DROP TABLE IF EXISTS hotel;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS employee_role;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS client_type;
DROP TABLE IF EXISTS person;