CREATE ROLE anon noinherit;
CREATE ROLE authenticator noinherit;

REVOKE ALL
ON ALL TABLES IN SCHEMA public 
FROM PUBLIC;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public 
TO anon;

REVOKE ALL PRIVILEGES
ON ALL TABLES IN SCHEMA internal 
FROM PUBLIC;

REVOKE ALL PRIVILEGES
ON ALL TABLES IN SCHEMA internal 
FROM anon;

GRANT anon TO authenticator;
