CREATE ROLE anon noinherit;
CREATE ROLE authenticator noinherit;

REVOKE ALL
ON ALL TABLES IN SCHEMA public 
FROM PUBLIC;

REVOKE ALL
ON ALL SEQUENCES IN SCHEMA public 
FROM PUBLIC;

GRANT ALL PRIVILEGES
ON ALL TABLES IN SCHEMA public 
TO anon;

GRANT ALL PRIVILEGES
ON ALL SEQUENCES IN SCHEMA public 
TO anon;

REVOKE ALL PRIVILEGES
ON ALL TABLES IN SCHEMA internal 
FROM anon;

REVOKE ALL PRIVILEGES
ON ALL SEQUENCES IN SCHEMA internal 
FROM anon;

GRANT anon TO authenticator;
